// This file is auto-generated by @lark-apaas/fullstack-cli
import { NestFactory } from '@nestjs/core';
import { DevToolsV2Module } from '@lark-apaas/fullstack-nestjs-core';

import { AppModule } from '../server/app.module';

/**
 * 生成 OpenAPI 文档和客户端 SDK
 *
 * 此文件由 @lark-apaas/fullstack-cli 自动派生，请勿手动修改
 * 每次运行 npm install 时会自动更新
 */
async function generateOpenApi() {
  const app = await NestFactory.create(AppModule, { logger: false });
  const basePath = process.env.CLIENT_BASE_PATH;

  if (basePath) {
    app.setGlobalPrefix(basePath);
  }

  await DevToolsV2Module.mount(app, {
    basePath,
    docsPath: '/api_docs',
    needSetupServer: false,
    needGenerateClientSdk: true,
  });
  
  process.exit(0); // 主动退出进程，不等待 app 关闭（用户存在场景，未释放 timer 导致 app 卡死问题）
}

generateOpenApi().catch((err) => {
  console.error('[OpenAPI] Failed to generate schema', err);
  process.exitCode = 1;
});
